export const UPDATE_UI = 'UPDATE_UI'

export const OPEN_CHOICE_WALLET = 'OPEN_CHOICE_WALLET'
export const CLOSE_CHOICE_WALLET = 'CLOSE_CHOICE_WALLET'

export const OPEN_RESTORE_WALLET = 'OPEN_RESTORE_WALLET'
export const CLOSE_RESTORE_WALLET = 'CLOSE_RESTORE_WALLET'

export const SET_ACTION = 'SET_ACTION'
