export const INIT_APP = 'INIT_APP'
export const SET_COINS = 'SET_COINS'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_KEY = 'SET_KEY'
export const VALIDATE_KEY = 'VALIDATE_KEY'
export const SET_ENDPOINT = 'SET_ENDPOINT'
export const INIT_COIN = 'INIT_COIN'
export const SET_USED_COIN = 'SET_USED_COIN'
